// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AnotherCurrencyShop","status":true,"description":"ゴールドではなく、変数の値で売買を行うショップを表示します","parameters":{"Currency Name":"MP","Variable Number":"1","Buy Command Name":"交換","Sell Command Name":"返却"}}
];
