// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AnotherCurrencyShop","status":true,"description":"ゴールドではなく、変数の値で売買を行うショップを表示します","parameters":{"currencyName":"ＰＴ","variableNumber":"1"}}
];
